# This is a basic workflow to help you get started with Actions
name: Test project
# Controls when the workflow will run
on: push
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # name of your choice
  test:
    #choose runner for execution environment
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        # Runs a single command using the runners shell
      - name: Get code
        # uses: comand for actions, and run: for running scripts
        # @v3 locking versions for the action
        uses: actions/checkout@v3
        
        # additional configuration can be checked in documentation for this action
        #with:
      
        #Preinstalled for ubuntu
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-versions: 18
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
